name: questionable content
favicon: null
layout_spectrum: 0.44056
typography_spectrum: 0.41032763198018074
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.07613728079013526
  lightness: 0.16661477275192738
  saturation: 0.4988833134993911
  rhythmicContrast: 0.9134928500279784
purpose: []
